# Generated by Django 3.2.3 on 2025-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=3, upload_to='', verbose_name='Выберите фото'),
            preserve_default=False,
        ),
    ]
