# Generated by Django 4.2.20 on 2025-03-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
