# Generated by Django 4.2.20 on 2025-03-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subscribes_delete_follow_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribes',
            new_name='Subscribe',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='api_subscribes_prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('subscription')), _negated=True), name='api_subscribe_prevent_self_follow'),
        ),
    ]
